# Generated by Django 3.2 on 2024-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20240520_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'year')},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
