# Generated by Django 3.2 on 2024-05-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20240524_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='XXXXX', max_length=5, null=True, verbose_name='код подтверждения'),
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
